# Generated by Django 4.1.3 on 2022-11-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='cotent',
            new_name='content',
        ),
    ]
