# Generated by Django 4.1.3 on 2022-12-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_rename_cotent_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sender', models.CharField(max_length=15)),
                ('receiver', models.CharField(max_length=15)),
                ('sent_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
