# Generated by Django 4.1.3 on 2022-12-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='out_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
