# Generated by Django 4.1.3 on 2022-12-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_conversations_out_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='out_message',
        ),
    ]
